--[[
atomic_transition.lua

Atomically validates and applies a session state change entirely inside
Redis, eliminating the read-check-write race that exists when the check and
the write happen as two separate round trips from the client.

KEYS[1] = session redis key, e.g. "session:{session_id}"

ARGV[1] = mode                      ("transition" | "revert")
ARGV[2] = new_status
ARGV[3] = updated_at                (ISO-8601 string, generated by the caller
                                      so the result is deterministic across
                                      replicas/AOF replay)
ARGV[4] = metadata_json             (JSON object string to shallow-merge into
                                      the session hash; pass "{}" if none)
ARGV[5] = transitions_json          (JSON object mapping status -> array of
                                      allowed next statuses, i.e. a JSON
                                      encoding of SessionManager.VALID_TRANSITIONS;
                                      only read when mode == "transition")
ARGV[6] = expected_current_status   (only read when mode == "revert" — a
                                      compare-and-set guard so a revert only
                                      applies if nobody else moved the
                                      session on in the meantime)

Why two modes: a forward transition must obey VALID_TRANSITIONS (e.g.
QUEUED -> PROCESSING is legal). But reverting after a downstream failure
(e.g. QUEUED -> PROCESSING succeeded in Redis, then the Postgres write
failed) needs to go PROCESSING -> QUEUED, which is *not* a legal forward
transition and would always be rejected by the transitions table. A revert
is therefore validated differently: via compare-and-set against
expected_current_status rather than against VALID_TRANSITIONS.

Returns a JSON-encoded string (decode with json.loads on the Python side):
  {"status": "ok", "old_status": "...", "new_status": "..."}
  {"status": "not_found"}
  {"status": "corrupt_state"}
  {"status": "invalid_transition", "current_status": "...", "attempted_status": "..."}   (mode == "transition")
  {"status": "revert_conflict", "current_status": "...", "expected_status": "..."}       (mode == "revert")
  {"status": "invalid_mode"}

Redis executes a single Lua script as one atomic, uninterruptible unit, so no
other command (including another invocation of this same script) can run
between the GET and the SET below. That's what makes this safe under
concurrency without needing WATCH/MULTI or client-side locking.
--]]

local key = KEYS[1]

local mode = ARGV[1]
local new_status = ARGV[2]
local updated_at = ARGV[3]
local metadata_json = ARGV[4]
local transitions_json = ARGV[5]
local expected_current_status = ARGV[6]

local raw = redis.call('GET', key)
if not raw then
    return cjson.encode({status = "not_found"})
end

local decode_ok, session = pcall(cjson.decode, raw)
if not decode_ok or type(session) ~= "table" then
    return cjson.encode({status = "corrupt_state"})
end

local current_status = session["status"]

if mode == "transition" then
    local transitions_ok, transitions = pcall(cjson.decode, transitions_json)
    if not transitions_ok then
        return cjson.encode({status = "corrupt_state"})
    end

    local allowed = transitions[current_status]
    local is_valid = false
    if allowed ~= nil then
        for _, candidate in ipairs(allowed) do
            if candidate == new_status then
                is_valid = true
                break
            end
        end
    end

    if not is_valid then
        return cjson.encode({
            status = "invalid_transition",
            current_status = current_status,
            attempted_status = new_status,
        })
    end

elseif mode == "revert" then
    -- Compare-and-set: only revert if nobody else has moved the session on
    -- since our forward transition landed. Deliberately bypasses
    -- VALID_TRANSITIONS, since a revert is not itself a pipeline move.
    if current_status ~= expected_current_status then
        return cjson.encode({
            status = "revert_conflict",
            current_status = current_status,
            expected_status = expected_current_status,
        })
    end

else
    return cjson.encode({status = "invalid_mode"})
end

-- Shallow-merge any extra metadata the caller wants stored alongside the
-- status change (e.g. error_message, risk_score).
local meta_ok, meta = pcall(cjson.decode, metadata_json)
if meta_ok and type(meta) == "table" then
    for k, v in pairs(meta) do
        session[k] = v
    end
end

session["status"] = new_status
session["updated_at"] = updated_at

-- KEEPTTL preserves any existing expiry on the key instead of resetting it
-- (requires Redis >= 6.0; drop the flag if you're on an older server).
redis.call('SET', key, cjson.encode(session), 'KEEPTTL')

return cjson.encode({
    status = "ok",
    old_status = current_status,
    new_status = new_status,
})