global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: "intelliview-orchestrator"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "fastapi:8000"

  - job_name: "celery-worker"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "worker:9101"

  - job_name: "celery-exporter"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "celery-exporter:9540"

  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"