"""create initial tables

Revision ID: d7d869570be9
Revises:
Create Date: 2026-07-11 14:50:22.937273

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d7d869570be9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidates",
        sa.Column("candidate_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("resume_text", sa.String(length=10000), nullable=True),
        sa.Column("skills", sa.JSON(), nullable=True),
        sa.Column("interview_history", sa.JSON(), nullable=True),
        sa.Column("avg_score", sa.Float(), nullable=True),
        sa.Column("total_interviews", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("candidate_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_candidates_candidate_id"), "candidates", ["candidate_id"], unique=False)
    op.create_table(
        "interview_sessions",
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column("candidate_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("assigned_node", sa.String(length=255), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("video_analysis", sa.JSON(), nullable=True),
        sa.Column("audio_analysis", sa.JSON(), nullable=True),
        sa.Column("evaluation_analysis", sa.JSON(), nullable=True),
        sa.Column("questions_asked", sa.JSON(), nullable=True),
        sa.Column("answers_provided", sa.JSON(), nullable=True),
        sa.Column("feedback_generated", sa.JSON(), nullable=True),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("template_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        op.f("ix_interview_sessions_candidate_id"), "interview_sessions", ["candidate_id"], unique=False
    )
    op.create_index(
        op.f("ix_interview_sessions_session_id"), "interview_sessions", ["session_id"], unique=False
    )
    op.create_table(
        "interview_templates",
        sa.Column("template_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("interview_type", sa.String(length=50), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("question_count", sa.Integer(), nullable=False),
        sa.Column("category_distribution", sa.JSON(), nullable=True),
        sa.Column("difficulty_distribution", sa.JSON(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("success_rate", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("template_id"),
    )
    op.create_index(
        op.f("ix_interview_templates_interview_type"), "interview_templates", ["interview_type"], unique=False
    )
    op.create_index(
        op.f("ix_interview_templates_template_id"), "interview_templates", ["template_id"], unique=False
    )
    op.create_table(
        "questions",
        sa.Column("question_id", sa.String(length=255), nullable=False),
        sa.Column("text", sa.String(length=1000), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("difficulty", sa.String(length=20), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("avg_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("question_id"),
    )
    op.create_index(op.f("ix_questions_category"), "questions", ["category"], unique=False)
    op.create_index(op.f("ix_questions_question_id"), "questions", ["question_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_questions_question_id"), table_name="questions")
    op.drop_index(op.f("ix_questions_category"), table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_interview_templates_template_id"), table_name="interview_templates")
    op.drop_index(op.f("ix_interview_templates_interview_type"), table_name="interview_templates")
    op.drop_table("interview_templates")
    op.drop_index(op.f("ix_interview_sessions_session_id"), table_name="interview_sessions")
    op.drop_index(op.f("ix_interview_sessions_candidate_id"), table_name="interview_sessions")
    op.drop_table("interview_sessions")
    op.drop_index(op.f("ix_candidates_candidate_id"), table_name="candidates")
    op.drop_table("candidates")
    # ### end Alembic commands ###
